image: vookimedlo/ubuntu-qt:latestDistroOfficial_gcc_bionic
    
stages:
    - build
    - test
    
build-qt:
    stage: build
    script: 
            - cd StockTicker
            - qmake
            - make

unit-tests:
    stage: test
    before_script:
            - sudo apt-get update
            - yes | apt-get install libqt5test5
    variables: 
        QT_QPA_PLATFORM: "offscreen"
    script: 
            - cd StockTicker
            - cd unittests
            - cd build
            - make
            - ./unittests
