image: vookimedlo/ubuntu-qt:latestDistroOfficial_gcc_bionic
    
stages:
    - build
    - test
    
build-qt:
    stage: build
    script: 
            - cd StockTicker
            - qmake
            - make

unit-tests:
    stage: test
    script: 
            - apt-get update
            - apt-get install libqt5test5
            - cd StockTicker
            - cd unittests
            - cd build
            - make
            - ./unittests
