stages:
    - build
    - test
    
build-qt:
    image: image: vookimedlo/ubuntu-qt:latestDistroOfficial_gcc_bionic
    stage: build
    script: 
            - cd StockTicker
            - qmake
            - make

unit-tests:
    image: approximator/qttest
    stage: test
    script: 
            - cd StockTicker
            - cd unittests
            - cd build
            - make
            - ./unittests
